### ISSUE TITLE
403 Forbidden - Cloudflare captcha

### ISSUE THREAD

**Issue by a17levine** [azoff/tockstalk#1] opened 2023-10-04 05:35 UTC
This is an awesome project but I think Tock caught on with Cloudflare capcha checks.

I tried running it just now and I got a 403 forbidden. When I went into Cypress and tried to load the page I kept getting this.

<img width="963" alt="image" src="https://github.com/azoff/tockstalk/assets/3523841/11da7ccc-b1c1-4a1a-a8b7-a6e396454472">

**Comment by azoff** [comment] 2023-10-04 05:39
Ahh bummer- I'll try to fix it next time I'm in need of using the plugin- or feel free to do so yourself. The approach I would use is to leverage nopecha's API: https://developers.nopecha.com/

Their tools are amazing for bypassing this sort of thing.

**Comment by azoff** [comment] 2024-02-26 08:11
See [this comment](https://github.com/azoff/tockstalk/issues/4#issuecomment-1963536559). Should be fixed in [v1.1.1](https://github.com/azoff/tockstalk/releases/tag/v1.1.0). Closing as a duplicate of #4

**Closed by azoff** 2024-02-26 08:11 UTC
